const words = [
  { word: "어벤져스", category: "영화" },
  { word: "매트릭스", category: "영화" },
  { word: "라라랜드", category: "영화" },
  { word: "메이즈러너", category: "영화" },
  { word: "택시운전사", category: "영화" },
  { word: "명량", category: "영화" },
  { word: "트랜스포머", category: "영화" },
  { word: "쏘우", category: "영화" },
  { word: "곤지암", category: "영화" },
  { word: "반지의 제왕", category: "영화" },
  { word: "해리포터", category: "영화" },
  { word: "캐리비안의 해적", category: "영화" },
  { word: "아바타", category: "영화" },
  { word: "실미도", category: "영화" },
  { word: "국제시장", category: "영화" },
  { word: "원피스", category: "애니메이션" },
  { word: "나루토", category: "애니메이션" },
  { word: "이누야샤", category: "애니메이션" },
  { word: "명탐정 코난", category: "애니메이션" },
  { word: "슬램덩크", category: "애니메이션" },
  { word: "드래곤볼", category: "애니메이션" },
  { word: "토토로", category: "애니메이션" },
  { word: "시간을 달리는 소녀", category: "애니메이션" },
  { word: "하울의 움직이는성", category: "애니메이션" },
  { word: "고양이의 보은", category: "애니메이션" },
  { word: "너의 이름은", category: "애니메이션" },
  { word: "센과치히로의 행방불명", category: "애니메이션" },
  { word: "맥도날드", category: "패스트푸드" },
  { word: "롯데리아", category: "패스트푸드" },
  { word: "KFC", category: "패스트푸드" },
  { word: "버거킹", category: "패스트푸드" },
  { word: "맘스터치", category: "패스트푸드" },
  { word: "미스터피자", category: "패스트푸드" },
  { word: "도미노피자", category: "패스트푸드" },
  { word: "피자헛", category: "패스트푸드" },
  { word: "피자스쿨", category: "패스트푸드" },
  { word: "피자에땅", category: "패스트푸드" },
  { word: "치킨매니아", category: "패스트푸드" },
  { word: "BBQ", category: "패스트푸드" },
  { word: "BHC", category: "패스트푸드" },
  { word: "굽네치킨", category: "패스트푸드" },
  { word: "네네치킨", category: "패스트푸드" },
  { word: "교촌치킨", category: "패스트푸드" },
  { word: "또래오래", category: "패스트푸드" },
  { word: "호식이2마리치킨", category: "패스트푸드" },
  { word: "북한", category: "나라" },
  { word: "일본", category: "나라" },
  { word: "미국", category: "나라" },
  { word: "독일", category: "나라" },
  { word: "프랑스", category: "나라" },
  { word: "러시아", category: "나라" },
  { word: "가나", category: "나라" },
  { word: "이집트", category: "나라" },
  { word: "인도", category: "나라" },
  { word: "중국", category: "나라" },
  { word: "호주", category: "나라" },
  { word: "노르웨이", category: "나라" },
  { word: "스위스", category: "나라" },
  { word: "캐나다", category: "나라" },
  { word: "리그오브레젼드", category: "게임" },
  { word: "배틀그라운드", category: "게임" },
  { word: "오버워치", category: "게임" },
  { word: "메이플", category: "게임" },
  { word: "리니지", category: "게임" },
  { word: "스타크래프트", category: "게임" },
  { word: "피파온라인", category: "게임" },
  { word: "겟엠프드", category: "게임" },
  { word: "디아블로", category: "게임" },
  { word: "마비노기", category: "게임" },
  { word: "포트리스", category: "게임" },
  { word: "경찰", category: "직업" },
  { word: "소방관", category: "직업" },
  { word: "교사", category: "직업" },
  { word: "의사", category: "직업" },
  { word: "국회의원", category: "직업" },
  { word: "버스기사", category: "직업" },
  { word: "학원강사", category: "직업" },
  { word: "택배기사", category: "직업" },
  { word: "목사", category: "직업" },
  { word: "중", category: "직업" },
  { word: "지하철기사", category: "직업" },
  { word: "통역관", category: "직업" },
  { word: "대통령", category: "직업" },
  { word: "편의점점원", category: "직업" },
  { word: "쇼트트랙", category: "스포츠" },
  { word: "컬링", category: "스포츠" },
  { word: "스피드스케이팅", category: "스포츠" },
  { word: "역도", category: "스포츠" },
  { word: "펜싱", category: "스포츠" },
  { word: "배드민턴", category: "스포츠" },
  { word: "테니스", category: "스포츠" },
  { word: "양궁", category: "스포츠" },
  { word: "사격", category: "스포츠" },
  { word: "마라톤", category: "스포츠" },
  { word: "스노우보드", category: "스포츠" },
  { word: "탁구", category: "스포츠" },
  { word: "럭비", category: "스포츠" },
  { word: "축구", category: "스포츠" },
  { word: "농구", category: "스포츠" },
];

const chooseWord = () => words[Math.floor(Math.random() * words.length)];

module.exports = { chooseWord };
